//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManiaxHub.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class DailyRecord
    {
        public long RecordID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<int> Coins { get; set; }
        public Nullable<int> Food { get; set; }
        public string StartingTime { get; set; }
        public string EndingTime { get; set; }
        public Nullable<int> TotalAmount { get; set; }
        public Nullable<int> Balance { get; set; }
        public double Credit { get; set; }
        public double Debit { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
